# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  user:  
    description: 'github username'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  entrypoint: '/check-hello-world.sh'
  args:
    - ${{ inputs.user }}